name: Desplegando pagina estatica en S3 3
on: workflow_dispatch
    
jobs:
 deploy:
   runs-on: ubuntu-latest


   steps:
     - name: Checkout repository ğŸ˜Š
       uses: actions/checkout@v4


     - name: Set up AWS CLI ğŸ’•
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-2


     - name: Deploy to AWS S3 ğŸ˜¶â€ğŸŒ«ï¸
       run: |
         aws s3 sync . s3://pagina-static-devops --delete
